### ISSUE TITLE
Error during building of Android64-Project with Skia4Delphi 6.2

### ISSUE THREAD

**Issue by philippjhofmann** [skia4delphi/skia4delphi#321]
Hi, until now I've used Skia4Delphi 6.1 but after the update to 6.2 I got the following error:

[DCC Error] E2597 C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Skia4Delphi\\Binary\\Static\\Android64\libsk4d.a(libskia.SkTypeface.o): In function `SkTypeface::GetDefaultTypeface(SkTypeface::Style)':
  SkTypeface.cpp:(.text._ZN10SkTypeface18GetDefaultTypefaceENS_5StyleE+0x1c8): undefined reference to `__cxa_guard_acquire'
  SkTypeface.cpp:(.text._ZN10SkTypeface18GetDefaultTypefaceENS_5StyleE+0x1f0): undefined reference to `__cxa_guard_release'
  C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\CatalogRepository\\AndroidNDK-21-23.0.51961.7529\\android-ndk-r21\\sources\\cxx-stl\\llvm-libc++\\libs\\arm64-v8a\libc++_static.a(locale.o): In function `std::__ndk1::__cloc()':
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:75: undefined reference to `__cxa_guard_acquire'
...

How can this be fixed or do I have to revert to Skia4Delphi 6.1?

Best regards, Philipp

**Comment by philippjhofmann** [comment]
It's seems to be fine after deactivating Skia4Delphi once and activate it again.

**Comment by philippjhofmann** [comment]
For Android32 the error is

[DCC Error] E2597 C:\Daten\Philipp\Delphi-Projects\icTrainerNext\Android\Release\System.Skia.API.o:System.Skia.API:function System::Skia::Api::LINKLIB_EGL(): error: undefined reference to 'LINKLIB_EGL'
  C:\Daten\Philipp\Delphi-Projects\icTrainerNext\Android\Release\System.Skia.API.o:System.Skia.API:function System::Skia::Api::LINKLIB_GLESv2(): error: undefined reference to 'LINKLIB_GLESv2'
  C:\Daten\Philipp\Delphi-Projects\icTrainerNext\Android\Release\System.Skia.API.o:System.Skia.API:function System::Skia::Api::LINKLIB_log(): error: undefined reference to 'LINKLIB_log'
  C:\Daten\Philipp\Delphi-Projects\icTrainerNext\Android\Release\System.Skia.API.o:System.Skia.API:function System::Skia::Api::LINKLIB_cxxstatic(): error: undefined reference to 'LINKLIB_cxxstatic'
  C:\Daten\Philipp\Delphi-Projects\icTrainerNext\Android\Release\System.Skia.API.o:System.Skia.API:function System::Skia::Api::LINKLIB_cxxabi(): error: undefined reference to 'LINKLIB_cxxabi'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(sk4d.sk4d_particleeffect.o):sk4d_particleeffect.cpp:function SkFromJsonVisitor::get(char const*): error: undefined reference to '__cxa_guard_acquire'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(sk4d.sk4d_particleeffect.o):sk4d_particleeffect.cpp:function SkFromJsonVisitor::get(char const*): error: undefined reference to '__cxa_guard_release'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libskia.SkBlendModeBlender.o):SkBlendModeBlender.cpp:function SkBlender::Mode(SkBlendMode): error: undefined reference to '__cxa_guard_acquire'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libskia.SkBlendModeBlender.o):SkBlendModeBlender.cpp:function SkBlender::Mode(SkBlendMode): error: undefined reference to '__cxa_guard_release'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libskia.SkBlendModeBlender.o):SkBlendModeBlender.cpp:function SkBlender::Mode(SkBlendMode): error: undefined reference to '__cxa_guard_acquire'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libskia.SkBlendModeBlender.o):SkBlendModeBlender.cpp:function SkBlender::Mode(SkBlendMode): error: undefined reference to '__cxa_guard_release'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libskia.SkBlendModeBlender.o):SkBlendModeBlender.cpp:function SkBlender::Mode(SkBlendMode): error: undefined reference to '__cxa_guard_acquire'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libskia.SkBlendModeBlender.o):SkBlendModeBlender.cpp:function SkBlender::Mode(SkBlendMode): error: undefined reference to '__cxa_guard_release'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(raw.SkRawCodec.o):SkRawCodec.cpp:function std::__ndk1::__throw_length_error(char const*): error: undefined reference to 'std::length_error::~length_error()'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(raw.SkRawCodec.o):SkRawCodec.cpp:function std::length_error::length_error(char const*): error: undefined reference to 'vtable for std::length_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libdng_sdk.dng_color_space.o):dng_color_space.cpp:function dng_space_sRGB::Get(): error: undefined reference to '__cxa_guard_abort'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libdng_sdk.dng_color_space.o):dng_color_space.cpp:function dng_space_ProPhoto::Get(): error: undefined reference to '__cxa_guard_abort'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libicu.rbbi.o):rbbi.cpp:function icu::RuleBasedBreakIterator::operator==(icu::BreakIterator const&) const: error: undefined reference to '__cxa_bad_typeid'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libicu.schriter.o):schriter.cpp:function icu::StringCharacterIterator::operator==(icu::ForwardCharacterIterator const&) const: error: undefined reference to '__cxa_bad_typeid'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libicu.uchriter.o):uchriter.cpp:function icu::UCharCharacterIterator::operator==(icu::ForwardCharacterIterator const&) const: error: undefined reference to '__cxa_bad_typeid'
  C:\\Daten\\Philipp\\Programme\\Skia4Delphi\\Binary\\Static\\Android/libsk4d.a(libicu.ustrenum.o):ustrenum.cpp:function icu::StringEnumeration::operator==(icu::StringEnumeration const&) const: error: undefined reference to '__cxa_bad_typeid'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'typeinfo for std::overflow_error'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'std::overflow_error::~overflow_error()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'vtable for std::overflow_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\CatalogRepository\\AndroidNDK-21-23.0.51961.7529\\android-ndk-r21\\sources\\cxx-stl\\llvm-libc++\\libs\\armeabi-v7a/libc++_static.a(ios.o):ios.cpp:vtable for std::__ndk1::ios_base::failure: error: undefined reference to 'std::runtime_error::what() const'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:75: error: undefined reference to '__cxa_guard_abort'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:0: error: undefined reference to 'typeinfo for std::runtime_error'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:0: error: undefined reference to 'std::runtime_error::~runtime_error()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:494: error: undefined reference to '__cxa_guard_abort'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:0: error: undefined reference to 'typeinfo for std::runtime_error'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/locale.cpp:0: error: undefined reference to 'std::runtime_error::~runtime_error()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/support/runtime/stdexcept_default.ipp:0: error: undefined reference to 'vtable for std::logic_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/support/runtime/stdexcept_default.ipp:0: error: undefined reference to 'vtable for std::logic_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/support/runtime/stdexcept_default.ipp:0: error: undefined reference to 'vtable for std::logic_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/support/runtime/stdexcept_default.ipp:0: error: undefined reference to 'vtable for std::runtime_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/support/runtime/stdexcept_default.ipp:0: error: undefined reference to 'vtable for std::runtime_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/support/runtime/stdexcept_default.ipp:0: error: undefined reference to 'vtable for std::runtime_error'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'typeinfo for std::out_of_range'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'std::out_of_range::~out_of_range()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'vtable for std::out_of_range'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/string.cpp:0: error: undefined reference to 'typeinfo for std::out_of_range'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/string.cpp:0: error: undefined reference to 'std::out_of_range::~out_of_range()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/string.cpp:0: error: undefined reference to 'typeinfo for std::invalid_argument'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/string.cpp:0: error: undefined reference to 'std::invalid_argument::~invalid_argument()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'vtable for std::invalid_argument'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/stdexcept:0: error: undefined reference to 'vtable for std::out_of_range'
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.exe: the vtable symbol may be undefined because the class is missing its key function
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/system_error.cpp:281: error: undefined reference to 'std::runtime_error::~runtime_error()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/system_error.cpp:281: error: undefined reference to 'std::runtime_error::~runtime_error()'
  C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\CatalogRepository\\AndroidNDK-21-23.0.51961.7529\\android-ndk-r21\\sources\\cxx-stl\\llvm-libc++\\libs\\armeabi-v7a/libc++_static.a(system_error.o):system_error.cpp:vtable for std::__ndk1::system_error: error: undefined reference to 'std::runtime_error::what() const'
  C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\CatalogRepository\\AndroidNDK-21-23.0.51961.7529\\android-ndk-r21\\sources\\cxx-stl\\llvm-libc++\\libs\\armeabi-v7a/libc++_static.a(system_error.o):system_error.cpp:typeinfo for std::__ndk1::system_error: error: undefined reference to 'typeinfo for std::runtime_error'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/future.cpp:82: error: undefined reference to 'std::logic_error::~logic_error()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/future.cpp:82: error: undefined reference to 'std::logic_error::~logic_error()'
  /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/future.cpp:82: error: undefined reference to 'std::logic_error::~logic_error()'
  C:\\Users\\Public\\Documents\\Embarcadero\\Studio\\23.0\\CatalogRepository\\AndroidNDK-21-23.0.51961.7529\\android-ndk-r21\\sources\\cxx-stl\\llvm-libc++\\libs\\armeabi-v7a/libc++_static.a(future.o):future.cpp:vtable for std::__ndk1::future_error: error: undefined reference to 'std::logic_error::what() const'

**Comment by paulocesarbot** [comment]
Could you give us more information about the problem involving Android? We were unable to reproduce it locally.

Specifically, which version of RAD Studio are you using? Have you customized your NDK or BDS? Do you have another machine to test and see if it gives the same error, which could give us more details?

The description of the error here is very difficult to investigate when there is no way to reproduce it.

Best regards,

**Comment by philippjhofmann** [comment]
I'm using Delphi 12.1 (Patch 1). I have only one machine. 
The SDK/NDK path is
C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidSDK-2525-23.0.51961.7529
C:\Users\Public\Documents\Embarcadero\Studio\23.0\CatalogRepository\AndroidNDK-21-23.0.51961.7529\android-ndk-r21

So this should be the standard version from Delphi installation.

**Comment by viniciusfbb** [comment]
I couldn't reproduce it also. I'm using the same RAD 12.1 and same SDK/NDK and the demo `Skia4Delphi\Samples\Demo\FMX\Projects\RAD Studio 12 Athens\Skia4Delphi.dproj` is running fine.

**Comment by viniciusfbb** [comment]
@philippjhofmann Do you have any news?

**Comment by philippjhofmann** [comment]
I need to retest later, currently there is no time for this and I switched back to 6.1 again.

**Comment by philippjhofmann** [comment]
I retested it today and I got the same error again. But I can start your demo project without any problem and I can start a new project without any problem. So the question is why I can't link my existing project. I've removed all lot of dependencies and libraries yet, but without success.
I assume, I have to rebuild the project from the scratch but this needs one day of work to rebuild every setting step by step. If there is any hint, it's very appreciated.

**Comment by viniciusfbb** [comment]
@philippjhofmann If you share your .dproj, we might be able to find any issue.

**Comment by philippjhofmann** [comment]
Here is my fresh generated project-file and the same error happens after I've added all relevant pas-file (nothing more).
[icTrainerNext.zip](https://github.com/user-attachments/files/16651940/icTrainerNext.zip)

**Comment by philippjhofmann** [comment]
The first problem is that we are using the error-reporting from https://blog.grijjy.com/ since years to print a stack-trace for exceptions. This seems to be incompatible with your new Android-Libraries:

It's incompatible with the following request there:
[MyErrorReporting.zip](https://github.com/user-attachments/files/16662050/MyErrorReporting.zip)

function cxa_demangle(const mangled_name: MarshaledAString;
  output_buffer: MarshaledAString; length: NativeInt;
  out status: Integer): MarshaledAString; cdecl;
  external 'libc++abi.a' name '__cxa_demangle';

**Comment by philippjhofmann** [comment]
The second problem was a incompatibility with WinSoft-PDFium and Skia4Delphi for Android as there was the following linker-option necessary (perhaps only in an older version of WinSoft-PDFium):

SYMBOLS {
  global: 
    _ZN*;
    _ZZ*;
};

As I don't use WinSoftPDFium again, I removed this linker option now. 
So there is only my problem with 

Android64:
function cxa_demangle(const mangled_name: MarshaledAString;
  output_buffer: MarshaledAString; length: NativeInt;
  out status: Integer): MarshaledAString; cdecl;
  external 'libc++abi.a' name '__cxa_demangle';

Android32:
function cxa_demangle(const mangled_name: MarshaledAString;
  output_buffer: MarshaledAString; length: NativeInt;
  out status: Integer): MarshaledAString; cdecl;
  external {$IF (RTLVersion < 34)}'libgnustl_static.a'{$ELSE}'libc++abi.a'{$ENDIF} name '__cxa_demangle';

So it would be perfect, if you can check this. Thanks.

**Comment by viniciusfbb** [comment]
@philippjhofmann Thank you very much for the extra information. Finally I managed to reproduce the issue. I am attaching here a minimal project that uses GrijjyCloudLogging + Skia reproducing the issue.

[SkiaAndroidLinkerError.zip](https://github.com/user-attachments/files/16675975/SkiaAndroidLinkerError.zip)

Steps:
 - Open the attached project;
 - Build for Android64:
 **Exp:** No error.
 **Act:** ```[DCC Error] E2597 c:\\embt\\tp\\trunk\\lib\\Android64\\debug\libsk4d.a(libskia.SkSLModuleLoader.o): In function `std::__ndk1::__hash_table< SkSL::Modifiers, std::__ndk1::hash<SkSL::Modifiers>, std::__ndk1::equal_to<SkSL::Modifiers>, std::__ndk1::allocator<SkSL::Modifiers> >::rehash (unsigned long)': ...```

**Comment by viniciusfbb** [comment]
Also, the issue is happening on Android, iOS and macOS. The previous demo can reproduce it as well. It should be fixed ASAP.

**Comment by viniciusfbb** [comment]
@philippjhofmann In fact, the issue is related to the binaries [DelphiZeroMQ/libzmq-android64.a](https://github.com/grijjy/DelphiZeroMQ/blob/master/libzmq-android64.a) and [DelphiZeroMQ/libzmq-android32.a](https://github.com/grijjy/DelphiZeroMQ/blob/master/libzmq-android32.a) in which objects referring to `libc++_static.a` and `libc++abi.a` were accidentally included in these binaries, and must be reported to the authors.

If you add System.Skia.API on the uses before the first Grijjy.CloudLogging unit, it will works. On the same way, if you add `-lc++_static -lc++abi` on `Project Options > Building > Delphi Compiler > Linking > (Android platform) > Options passed to the LD Linker`, it will work.

On our side, we cannot do anything, as the root of the issue is not here.

**Comment by philippjhofmann** [comment]
Top support. Thanks. It works again also on our side.
