### ISSUE TITLE
Android - duplicate symbol errors

### ISSUE THREAD

**Issue by Spelt** [skia4delphi/skia4delphi#407]
Hi

Thanks for this awesome project.  Since migrating from 12.1 to 12.3 I am getting some weird Android issues with Skia. It has a conflict with the pdfium  library.  The errors are a lot of duplicate symbol errors. Below is one of them. 

[DCC Error] E2597 ld.lld: error: duplicate symbol: jpeg_natural_order
  >>> defined at jutils.c
  >>>            libjpeg.jutils.o:(jpeg_natural_order) in archive c:\\program files (x86)\\embarcadero\\studio\\23.0\\lib\\Android64\\Release/libsk4d.a
  >>> defined at jutils.c
  >>>            jutils.o:(.rodata+0x0) in archive ..\\..\\..\\Library\\Android64/libpdfium.a

etc.etc.etc.

It seems the error is described here: https://stackoverflow.com/questions/6116188/understanding-the-origin-of-a-linker-duplicate-symbol-error

I hope you or someone can help with this.

Regards, Edward
